### ISSUE TITLE
enable property and enabled method

### ISSUE THREAD

**Issue by hstarmans** [petebachant/ACSpy#14]
Dear all,

I really like ACSpy. At the moment, the axis object object, part of the control module, has an enabled property and an enable and disable method. Wouldn't it be better to define a setter for the enabled property, and then if one use true or false run disable or enable!?

**Comment by petebachant** [comment]
That sounds like a good idea!

**Comment by petebachant** [comment]
Something like this could work:

```python
    @property
    def enabled(self):
        return self.motor_state["enabled"]
    @enabled.setter
    def enabled(self, choice):
        if choice == True:
            self.enable()
        elif choice == False:
            self.disable()
```

**Comment by hstarmans** [comment]
Indeed, something like that! Some code elsewhere might be changed as well, or would you like to keep the old style.
```python
>>> from acspy.control import Controller
>>> controller = Controller(contype="simulator", n_axes=4)
>>> controller.connect()
>>> axis0 = controller.axes[0]
>>> axis0.enabled=True
>>> axis0.enabled
True
```

**Comment by petebachant** [comment]
I actually think the `axis0.enable()` version is a little more intuitive, but I think supporting both is fine.

**Comment by hstarmans** [comment]
I have made the pull request with your code, now two approaches are available.
