### ISSUE TITLE
DC Command

### ISSUE THREAD

**Issue by Alhassan-Khalil** [petebachant/ACSpy#28]
Hello ACSPY team,

I was wondering if there is a way to call DC command 
`DC [/switch] [axis], array_name, #_of_samples, period, list_of_variables `.
If not, how can I implement it? 
I want to call DC as a command in the communication terminal and when I am done I call `STOPDC [/switch] [integer]`.

I know I can do this by writing a buffer as 
```
prg = prg.ACSPLplusPrg()
prg.add_dc("X", "PosArr", sampleNumber, sampleTime, "TPOS(0) , FPOS(0)", "/s")
```
But I want to do it in Python instead of creating a buffer.

Thanks in advance

Best reagrds,
Alhassan

**Comment by petebachant** [comment]
I've never tried it. Is there a corresponding function in the ACS C library? If so, that could easily be wrapped.

**Comment by Alhassan-Khalil** [comment]
Thank you for the quick response! After looking into it further, I found the relevant function in the ACS C library
thank you for pointing me in the right direction.

Here’s the Python wrapper I created for acsc_Command:

```
def command(hcomm, command_str: str, wait=SYNCHRONOUS):
    """Sends a command to the ACS controller"""
    cmd_with_return = (command_str + '\r').encode()
    cmd_len = len(cmd_with_return)
    cmd_buffer = ctypes.create_string_buffer(cmd_with_return)
    result = call_acsc(acs.acsc_Command, hcomm, cmd_buffer, cmd_len, wait)
    return result != 0  
```

**Comment by petebachant** [comment]
Nice. I will submit a PR to add that to the `acsc` module here so others can use it.
