### ISSUE TITLE
encode string to UTF8 for compatibililty with python 3

### ISSUE THREAD

**Issue by hstarmans** [petebachant/ACSpy#8]
Dear Pete Bachant,

I am having a lot of fun with your work. Thanks for that :+1: . You should encode strings to "utf-8'.
Simple stated: 
hcomm=acsc.openCommEthernetTCP('192.168.1.40', 701) --> return -1 in python 3.5
hcomm=acsc.openCommEthernetTCP('192.168.1.40'.encode('utf-8'), 701) --> return 0

All my python 2.7 code was therefore not python 3 compatible. 
Ideally, I can supply strings from python 3 and they are encoded to "utf-8" in the library.

Best,

Rik

**Comment by petebachant** [comment]
Aha. I had never encountered this issue, though I think I have been able to run fine on Python 3+. Thanks for raising it. Can you make the changes (encode the string inside that function) and submit a pull request, including a test that will fail, maybe using the simulator in Python 3.5.

**Comment by hstarmans** [comment]
I will submit a fix. Probably, Thursday or next week.
